{% set name = "jupyter_contrib_core" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_contrib_core-{{ version }}.tar.gz
  sha256: ad995f5754188ab41ea5f94d69c9a1f96ba50543274d798d9001f937f730d326

build:
  noarch: python
  entry_points:
    - jupyter-contrib = jupyter_contrib_core.application:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - setuptools
    - jupyter_core
    - notebook >=4.0
    - tornado
    - traitlets

test:
  imports:
    - jupyter_contrib_core
    - jupyter_contrib_core.application
    - jupyter_contrib_core.notebook_compat
    - jupyter_contrib_core.notebook_compat.nbextensions
    - jupyter_contrib_core.notebook_compat.serverextensions
    - jupyter_contrib_core.notebook_compat._compat
    - jupyter_contrib_core.notebook_compat._compat.nbextensions
    - jupyter_contrib_core.notebook_compat._compat.serverextensions

test:
  imports:
    - jupyter_contrib_core
  commands:
    - pip check
    - jupyter-contrib --help
  requires:
    - pip

about:
  summary: Common utilities for jupyter-contrib projects.
  home: https://github.com/jupyter-contrib/jupyter_contrib_core
  license_file: LICENSE.txt
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - jcb91
    - ocefpaf
